import os
import uuid
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont
from moviepy import ImageClip

BASE_DIR = Path(__file__).resolve().parent
OUTPUT_DIR = BASE_DIR / "generated"
OUTPUT_DIR.mkdir(exist_ok=True)


def _wrap_text(text: str, max_chars: int = 28) -> list[str]:
    words = text.split()
    if not words:
        return [""]

    lines = []
    current = ""

    for word in words:
        trial = f"{current} {word}".strip()
        if len(trial) <= max_chars:
            current = trial
        else:
            if current:
                lines.append(current)
            current = word

    if current:
        lines.append(current)

    return lines[:6]


def _get_font(size: int):
    candidates = [
        "arial.ttf",
        "DejaVuSans-Bold.ttf",
        "DejaVuSans.ttf",
    ]

    for name in candidates:
        try:
            return ImageFont.truetype(name, size)
        except Exception:
            continue

    return ImageFont.load_default()


def create_video(
    prompt: str,
    duration_seconds: int = 5,
    watermark: str = "naijavid.ai",
    language: str = "English",
) -> str:
    width = 720
    height = 1280

    image = Image.new("RGB", (width, height), color=(10, 10, 14))
    draw = ImageDraw.Draw(image)

    title_font = _get_font(52)
    body_font = _get_font(42)
    small_font = _get_font(28)

    # Header
    draw.text((40, 60), "NaijaVid AI", font=title_font, fill=(255, 255, 255))
    draw.text((40, 135), f"Language: {language}", font=small_font, fill=(210, 210, 210))

    # Prompt block
    box_x1, box_y1, box_x2, box_y2 = 40, 220, width - 40, 900
    draw.rounded_rectangle(
        [box_x1, box_y1, box_x2, box_y2],
        radius=24,
        outline=(90, 90, 100),
        width=2,
        fill=(20, 20, 28),
    )

    lines = _wrap_text(prompt, max_chars=24)
    y = 280
    for line in lines:
        draw.text((70, y), line, font=body_font, fill=(255, 255, 255))
        y += 72

    # Footer
    draw.text((40, height - 120), watermark, font=small_font, fill=(255, 215, 0))
    draw.text((40, height - 80), "Generated by NaijaVid AI", font=small_font, fill=(170, 170, 170))

    filename = f"{uuid.uuid4().hex}.png"
    image_path = OUTPUT_DIR / filename
    image.save(image_path)

    video_name = f"{uuid.uuid4().hex}.mp4"
    video_path = OUTPUT_DIR / video_name

    clip = ImageClip(str(image_path), duration=duration_seconds)
    clip.write_videofile(
        str(video_path),
        fps=24,
        codec="libx264",
        audio=False,
    )

    try:
        os.remove(image_path)
    except Exception:
        pass

    return video_name